<!doctype html>
<html lang="en-us">
  <head>
    <title>记录PIP安装出现的一系列错误 // 木哈文轩</title>
    <link rel="shortcut icon" href="/favicon.ico" />
    <meta charset="utf-8" />
    <meta name="generator" content="Hugo 0.123.3">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="author" content="木木em哈哈" />
    <meta name="description" content="文章浏览阅读982次。反应过来这是因为用的是国内源所以下载速度慢，而且容易丢包，而且要命的是pip不支持断点续传结果文件下载失败，文件都不完整，安装出现时候自然出现一系列错误。注意看，我在打代码时忘记打-i原本应该为。因为过于愚蠢结果百度的搜不出来。执行前面的命令终于安装成功了。那好办我用国内源不就行了？在安装pandas时运行。我还没发现，结果出现报错。_status=run_func(*args)报错pip" />
    <link rel="stylesheet" href="/css/main.min.a545955c4c2a15328ae3f208fda979c3a40146d5a6d4f95e0ab1a00e48cd1ff2.css" />
    

    
    <meta name="twitter:card" content="summary"/><meta name="twitter:title" content="记录PIP安装出现的一系列错误"/>
<meta name="twitter:description" content="文章浏览阅读982次。反应过来这是因为用的是国内源所以下载速度慢，而且容易丢包，而且要命的是pip不支持断点续传结果文件下载失败，文件都不完整，安装出现时候自然出现一系列错误。注意看，我在打代码时忘记打-i原本应该为。因为过于愚蠢结果百度的搜不出来。执行前面的命令终于安装成功了。那好办我用国内源不就行了？在安装pandas时运行。我还没发现，结果出现报错。_status=run_func(*args)报错pip"/>

    <meta property="og:title" content="记录PIP安装出现的一系列错误" />
<meta property="og:description" content="文章浏览阅读982次。反应过来这是因为用的是国内源所以下载速度慢，而且容易丢包，而且要命的是pip不支持断点续传结果文件下载失败，文件都不完整，安装出现时候自然出现一系列错误。注意看，我在打代码时忘记打-i原本应该为。因为过于愚蠢结果百度的搜不出来。执行前面的命令终于安装成功了。那好办我用国内源不就行了？在安装pandas时运行。我还没发现，结果出现报错。_status=run_func(*args)报错pip" />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://0ha.top/posts/130396342/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2023-05-28T11:28:15+00:00" />
<meta property="article:modified_time" content="2023-05-28T11:28:15+00:00" />



  </head>
  <body>
    <header class="app-header">
      <a href="https://0ha.top/"><img class="app-header-avatar" src="https://s3.bmp.ovh/imgs/2024/02/27/ebc3b3191cd37c75.jpg" alt="木木em哈哈" /></a>
      <span class="app-header-title">木哈文轩</span>
      <nav class="app-header-menu">
          <a class="app-header-menu-item" href="/">主页</a>
              ·  
          
          <a class="app-header-menu-item" href="/tags/">标签</a>
              ·  
          
          <a class="app-header-menu-item" href="/about/">有关</a>
      </nav>
      <p>别让我逮住嗷</p>
      <div class="app-header-social">
        
          <a href="https://blog.csdn.net/mumuemhaha" target="_blank" rel="noreferrer noopener me">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-circle">
  <title>CSDN</title>
  <circle cx="12" cy="12" r="10"></circle>
</svg>
          </a>
        
          <a href="https://github.com/mumuhaha487" target="_blank" rel="noreferrer noopener me">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-github">
  <title>Github</title>
  <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path>
</svg>
          </a>
        
      </div>
    </header>
    <main class="app-container">
      
  <article class="post">
    <header class="post-header">
      <h1 class ="post-title">记录PIP安装出现的一系列错误</h1>
      <div class="post-meta">
        <div>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-calendar">
  <title>calendar</title>
  <rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line>
</svg>
          May 28, 2023
        </div>
        <div>
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-clock">
  <title>clock</title>
  <circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>
</svg>
          2 min read
        </div>
      </div>
    </header>
    <div class="post-content">
      <p>在安装pandas时运行</p>
<pre tabindex="0"><code>pip install Pandas
</code></pre><p>结果出现报错</p>
<p><img src="https://0ha.top/img/e9b1a8fde3454a6bb5ef3cba02802445.png" alt=""></p>
<pre tabindex="0"><code>ERROR: Exception:
Traceback (most recent call last):
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 438, in _error_catcher
    yield
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 561, in read
    data = self._fp_read(amt) if not fp_closed else b&#34;&#34;
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py&#34;, line 90, in read
    data = self.__fp.read(amt)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\http\client.py&#34;, line 466, in read
    s = self.fp.read(amt)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\socket.py&#34;, line 705, in readinto
    return self._sock.recv_into(b)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\ssl.py&#34;, line 1274, in recv_into
    return self.read(nbytes, buffer)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\ssl.py&#34;, line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\cli\base_command.py&#34;, line 169, in exc_logging_wrapper
    status = run_func(*args)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\cli\req_command.py&#34;, line 248, in wrapper
    return func(self, options, args)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\commands\install.py&#34;, line 377, in run
    requirement_set = resolver.resolve(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py&#34;, line 92, in resolve
    result = self._result = resolver.resolve(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\resolvelib\resolvers.py&#34;, line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\resolvelib\resolvers.py&#34;, line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\resolvelib\resolvers.py&#34;, line 173, in _add_to_criteria
    if not criterion.candidates:
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\resolvelib\structs.py&#34;, line 156, in __bool__
    return bool(self._sequence)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py&#34;, line 155, in __bool__
    return any(self)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py&#34;, line 143, in &lt;genexpr&gt;
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py&#34;, line 47, in _iter_built
    candidate = func()
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py&#34;, line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py&#34;, line 293, in __init__
    super().__init__(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py&#34;, line 156, in __init__
    self.dist = self._prepare()
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py&#34;, line 225, in _prepare
    dist = self._prepare_distribution()
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py&#34;, line 304, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\operations\prepare.py&#34;, line 516, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\operations\prepare.py&#34;, line 587, in _prepare_linked_requirement
    local_file = unpack_url(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\operations\prepare.py&#34;, line 166, in unpack_url
    file = get_http_url(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\operations\prepare.py&#34;, line 107, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\network\download.py&#34;, line 147, in __call__
    for chunk in chunks:
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\cli\progress_bars.py&#34;, line 53, in _rich_progress_bar
    for chunk in iterable:
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_internal\network\utils.py&#34;, line 63, in response_chunks
    for chunk in response.raw.stream(
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 560, in read
    with self._error_catcher():
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\contextlib.py&#34;, line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File &#34;C:\Users\mumuemhaha\.conda\envs\mumuemhaha\lib\site-packages\pip\_vendor\urllib3\response.py&#34;, line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, &#34;Read timed out.&#34;)
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host=&#39;files.pythonhosted.org&#39;, port=443): Read timed out.&lt;/genexpr&gt;
</code></pre><p>好多红啊，吓我一跳</p>
<p>反应过来这是因为用的是国内源所以下载速度慢，而且容易丢包，而且要命的是pip不支持断点续传结果文件下载失败，文件都不完整，安装出现时候自然出现一系列错误。</p>
<p>那好办我用国内源不就行了？</p>
<pre tabindex="0"><code>pip install Pandas https://pypi.doubanio.com/simple
</code></pre><p>注意看，我在打代码时忘记打-i原本应该为</p>
<pre tabindex="0"><code>pip install Pandas -i https://pypi.doubanio.com/simple
</code></pre><p>我还没发现，结果出现报错</p>
<pre tabindex="0"><code>ERROR: Cannot unpack file C:\Users\mumuemhaha\AppData\Local\Temp\pip-unpack-njd05guz\simple.html (downloaded from C:\Users\mumuemhaha\AppData\Local\Temp\pip-req-build-44960vzz, content-type: text/html); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\mumuemhaha\AppData\Local\Temp\pip-req-build-44960vzz
</code></pre><p>我换了好几个镜像源</p>
<p>因为过于愚蠢结果百度的搜不出来</p>
<p>然后在一检查</p>
<p>真的被自己蠢到了</p>
<p>执行前面的命令终于安装成功了</p>
<p>（更新）</p>
<p>注意：换的源是https的协议的</p>

    </div>
    <div class="post-footer">
      
    </div>
  </article>

    </main>
  </body>
</html>
